name: rss_feed_build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  URL: ${{ secrets.URL }}
  TITLE: ${{ secrets.TITLE }}
  DESCRIPTION: ${{ secrets.DESCRIPTION }}
  REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}

jobs:
  rss_feed_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run rss_feed_build
      run: |
        sudo docker-compose build
        sudo docker-compose run \
          -e BASE_URL=${{ env.BASE_URL }} \
          -e URL=${{ env.URL }} \
          -e TITLE=${{ env.TITLE }} \
          -e DESCRIPTION=${{ env.DESCRIPTION }} \
          -e REPOSITORY_URL=${{ env.REPOSITORY_URL }} \
          -T app ruby lib/main.rb
    - name: git push
      run: |
        if [ `git status -z | wc -c` -gt 0 ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[rss_feed_build]"`date +%Y%m%d%H%M%S`
          git push origin main
        else
          echo "not changed"
        fi
